//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::ingredient::Entity as Ingredient;
pub use super::ingredient_price::Entity as IngredientPrice;
pub use super::recipe::Entity as Recipe;
pub use super::recipe_ingredient::Entity as RecipeIngredient;
pub use super::unit::Entity as Unit;
